### YamlMime:FAQ
metadata:
  title: 'Firewall de aplicaciones web en Application Gateway: preguntas más frecuentes'
  description: Este artículo proporciona respuestas a las preguntas más frecuentes sobre el Firewall de aplicaciones web en Application Gateway.
  services: web-application-firewall
  author: vhorne
  ms.service: web-application-firewall
  ms.topic: article
  ms.date: 05/05/2020
  ms.author: victorh
  ms.openlocfilehash: d7d5d5c9ea2c0af4933a7bff50ab310d95d29741
  ms.sourcegitcommit: c05e595b9f2dbe78e657fed2eb75c8fe511610e7
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 06/11/2021
  ms.locfileid: "112034944"
title: Preguntas más frecuentes sobre el Firewall de aplicaciones web de Azure en Application Gateway
summary: En este artículo se responden preguntas comunes sobre la funcionalidad y las características del Firewall de aplicaciones web (WAF) en Application Gateway.
sections:
- name: Omitido
  questions:
  - question: >
      ¿Qué es WAF de Azure?
    answer: >
      Azure WAF es un Firewall de aplicaciones web que ayuda a proteger sus aplicaciones web frente a amenazas comunes como inyección de código SQL, el scripting entre sitios y otras vulnerabilidades de seguridad de la web. Puede definir una directiva de WAF, que consta de una combinación de reglas personalizadas y administradas para controlar el acceso a sus aplicaciones web.


      Para las aplicaciones web hospedadas en el servicio Application Gateway o Azure Front Door, se puede aplicar una directiva de WAF de Azure.
  - question: >
      ¿Qué características admite la SKU de WAF?
    answer: >
      La SKU de WAF admite todas las características disponibles en la SKU Estándar.
  - question: >
      ¿Cómo se supervisa el WAF?
    answer: >
      Supervise WAF a través del registro de diagnóstico. Para más información, consulte [Diagnostic logging and metrics for Application Gateway](../../application-gateway/application-gateway-diagnostics.md) (Registro de diagnóstico y métricas de Application Gateway).
  - question: >
      ¿Bloquea el modo de detección el tráfico?
    answer: >
      No. El modo de detección solo registra el tráfico que desencadena una regla de WAF.
  - question: >
      ¿Se pueden personalizan las reglas de WAF?
    answer: >
      Sí. Para más información, consulte [Personalización de reglas de firewall de aplicaciones web mediante Azure Portal](application-gateway-customize-waf-rules-portal.md).
  - question: >
      ¿Qué reglas están disponibles actualmente para WAF?
    answer: "Actualmente, WAF admite CRS [2.2.9](application-gateway-crs-rulegroups-rules.md#owasp229), [3.0](application-gateway-crs-rulegroups-rules.md#owasp30) y [3.1](application-gateway-crs-rulegroups-rules.md#owasp31). Estas reglas proporcionan seguridad de línea base frente a la mayoría de las 10 vulnerabilidades principales que Open Web Application Security Project (OWASP) identifica: \n\n* Protección contra la inyección de código SQL\n* Protección contra ataques de scripts de sitios\n* Protección contra ataques web comunes, como la inyección de comandos, el contrabando de solicitudes HTTP, la división de respuestas HTTP y el ataque remoto de inclusión de archivos.\n* Protección contra infracciones del protocolo HTTP\n* Protección contra anomalías del protocolo HTTP, como la falta de agentes de usuario de host y encabezados de aceptación\n* Prevención contra bots, rastreadores y escáneres\n* Detección de errores de configuración comunes en aplicaciones (es decir, Apache, IIS, etc.).\n\nPara obtener más información, consulte las [10 vulnerabilidades principales de OWASP](https://owasp.org/www-project-top-ten/).\n"
  - question: >
      ¿Qué tipos de contenido admite WAF?
    answer: >
      Application Gateway WAF admiten los siguientes tipos de contenido para las reglas administradas:


      * application/json

      * aplicación/xml

      * application/x-www-form-urlencoded

      * multipart/form-data


      Y para las reglas personalizadas:


      * application/x-www-form-urlencoded

      * multipart/form-data
  - question: >
      ¿Admite WAF la protección contra DDoS?
    answer: >
      Sí. Puede habilitar la protección contra DDos en la red virtual donde se implementa Application Gateway. Esta configuración garantiza que el servicio Azure DDoS Protection también protege la IP virtual (VIP) de Application Gateway.


      ### <a name="does-waf-store-customer-data"></a>¿WAF almacena datos de los clientes?


      No, WAF no almacena datos de clientes.
additionalContent: "\n## <a name=\"next-steps\"></a>Pasos siguientes\n\n- Más información sobre [Firewall de aplicaciones web de Azure](../overview.md).\n- Obtenga más información acerca de [Azure Front Door](../../frontdoor/front-door-overview.md)."
